version: 1.1.1-{build}

environment:
  matrix:
  - GENERATOR: Visual Studio 14 2015
  - GENERATOR: Visual Studio 14 2015 Win64
  - GENERATOR: Visual Studio 12 2013
  - GENERATOR: Visual Studio 12 2013 Win64

configuration: Debug

install:
  - git submodule -q update --init --recursive

before_build:
  - cmake --version
  - mkdir build
  - cd build

build_script:
  - cmake -G "%GENERATOR%" ..
  - cmake --build . --config %CONFIGURATION%
